apiVersion: v1
kind: Pod
metadata:
   name: postinstall-hook
   annotations:
       "helm.sh/hook": "post-install"
       "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: post-install-container
    image: alpine:3.3
    imagePullPolicy: Always
    command: ['sh', '-c', 'echo Post-install hook finished && sleep 15' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0