apiVersion: v1
kind: Pod
metadata:
   name: postinstall-hook
   annotations:
      "helm.sh/hook": "post-install"
      "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: post-install-container
    image: imagebusy
    imagePullPolicy: Always
    command: ['sh', '-c', 'echo Post-install hook finished' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0