- name: Deploying web_app
  block:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory

    - name: Moving template to the dest
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ base_path }}/docker-compose.yml"
        owner: root
        group: root

    - name: Running docker-compose
      community.docker.docker_compose_v2:
        project_src: "{{ base_path }}"
        state: present
        pull: missing
  tags:
    - web_python

- name: Wipe the app
  import_tasks: 0-wipe.yml
  tags:
    - wipe_app
