name: GoTest
on: 
  push:
    paths:
      - 'app_go/*'
  workflow_dispatch:
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Golang
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache: false

            - name: Test
              run: |
                cd app_go
                go install && go test .

            - name: Docker Login
              run: |
                docker login --username {{secrets.DOCKER_USERNAME}} --password {{secrets.DOCKER_PASSWORD}}
    syk: 
      runs-on: ubuntu-latest
      steps:
        - name: Chekcout
          uses: actions/checkout@v3
          with:
            sparse-checkout: 'app_go/'
            sparse-checkout-cone-mode: false

        - name: Move Files
          run:
            mv ./app_go/* ./
            rm -rf ./app_go

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
              command: monitor