name: GoTest
on: push
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Golang
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache: false

            - name: Test
              run: |
                cd app_go
                go install && go test .