name: GoTest
on: 
  push:
    paths:
      - 'app_go/*'
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Golang
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache: false

            - name: Test
              run: |
                cd app_go
                go install && go test .

            - name: Docker Login
              run: |
                docker login --username {{secrets.DOCKER_USERNAME}} --password {{secrets.DOCKER_PASSWORD}}
            
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: monitor