name: Pytest
on:
  push:
    paths:
      - 'app_python/*'
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                sparse-checkout: 'app_python/'
                sparse-checkout-cone-mode: false

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: Install dependencies with pytest
              run: |
                pip install -r requirements.txt
                pip install pytest
            
            - name: Pytest
              run: |    
                pytest .

            - name: Docker Login
              run: |
                docker login --username {{secrets.DOCKER_USERNAME}} --password {{secrets.DOCKER_PASSWORD}}
            
            - name: Build & Push
              run: |
                docker build -t ramprin/devops:python ./app_python && docker push ramprin/devops:python

            - name: Snyk
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                command: monitor