name: Pytest
on: push
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: Install dependencies with pytest
              run: |
                cd app_python
                pip install -r requirements.txt
                pip install pytest
            
            - name: Pytest
              run: |    
                cd app_python
                pytest .